Today's assignment is about adopting one of the classification methods to retrain the model using various parameter values.

I adopted "Ensemble classifiers" (RandomForest and AdaBoost) and passed various values to it's parameter (n_estimator).

The initial value is 100, which resulted the accuracy of 79.0% for RandomForest and 58.4% for AdaBoost. Butr when you change the values especially different values i.e if you increase the value of RandomForest and decrease the value of AdaBoost. the accuracy will increased for both methods.

In [4]:
import pandas as pd 
quisine = pd.read_csv('C:/Users/PC/Desktop/new_cuisine.csv')
quisine.head()

,Unnamed: 0,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,...,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini,cuisine
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,indian
1,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,indian
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,indian
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,indian
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,indian

In [5]:
quisine_label_df = quisine['cuisine']
quisine_label_df.head()

0    indian
1    indian
2    indian
3    indian
4    indian
Name: cuisine, dtype: object

In [6]:
quisine_feature_df = quisine.drop(['Unnamed: 0', 'cuisine'], axis=1)
quisine_feature_df.head()

,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,artichoke,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [8]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, precision_score,confusion_matrix, classification_report, precision_recall_curve
import numpy as np

In [9]:
x_train, x_test, y_train, y_test = train_test_split(quisine_feature_df, quisine_label_df, train_size=0.3)

In [26]:

classifiers = {'RFST':RandomForestClassifier(n_estimators=150),
               'ADA':AdaBoostClassifier(n_estimators=50)}


n_classifier = len(classifiers)
for index, (name, classifier) in enumerate(classifiers.items()):
    classifier.fit(x_train, np.ravel(y_train))

    pred = classifier.predict(x_test)
    accuracy = accuracy_score(y_test, pred)

    print('Accuracy (train) for %s: %0.1f%%' % (name, accuracy*100))
    print(classification_report(y_test, pred))

Accuracy (train) for RFST: 79.4%
              precision    recall  f1-score   support

     chinese       0.64      0.83      0.72       547
      indian       0.88      0.91      0.89       565
    japanese       0.77      0.79      0.78       543
      korean       0.87      0.77      0.82       565
        thai       0.87      0.68      0.76       577

    accuracy                           0.79      2797
   macro avg       0.81      0.79      0.79      2797
weighted avg       0.81      0.79      0.80      2797

Accuracy (train) for ADA: 61.2%
              precision    recall  f1-score   support

     chinese       0.41      0.60      0.49       547
      indian       0.83      0.71      0.77       565
    japanese       0.55      0.48      0.51       543
      korean       0.73      0.62      0.67       565
        thai       0.66      0.65      0.65       577

    accuracy                           0.61      2797
   macro avg       0.64      0.61      0.62      2797
weighted avg       0.64      0.61      0.62      2797